### PR TITLE
Update meta packages to v60

### PR DESCRIPTION
**Pull request by StephenHodgson**
- updated unity engine to 2022.3.16f
- updated meta packages to v60
- removed empty editor folder
- removed package-lock.json
- updated .gitignore

### CODE REVIEW

**Comment by codeworks-studio** [comment]
Have the update to SDK 60 been commited? Currently this does not build, textmeshpro v3 to v4 in unity also needs a fix

**Comment by StephenHodgson** [comment]
I built and tested this just yesterday. 

What exactly are you running into?

**Comment by crien-xr** [comment]
Thanks for your pull request. We just pushed a commit that updates Phanto to v60 core SDK and adds support for Depth API and Haptics SDK.

**Comment by crien-xr** [comment]
> Have the update to SDK 60 been commited? Currently this does not build, textmeshpro v3 to v4 in unity also needs a fix

It looks like there's a problem building Phanto with Unity 2023.2.3 (not just this PR). I'll see if there's a solution, but you might want to open an issue so we can track this outside of this thread. Thanks.

**Comment by StephenHodgson** [comment]
Please pull these changes and test, I opened the PR in good faith as a contributor.

This PR will build and run as expected.

If there's any change requests or something else that would prevent me from contributing, please let me know.

**Pull request closed without merging**
